export {default as HeroSection} from "./home/hero/hero"
export {default as ServicesSection} from "./home/our-services/services"
export {default as ProductsSection} from "./home/products/products"
export {default as ArrivalsSection} from "./home/new-arivals/newArrival"
export {default as TestimonialsSection} from "./home/testimonials/testimonials"
export {default as CollectionsSection} from "./home/collections/collections"
export {default as DiscountSection} from "./home/discount/discount"
// export {default as SubHeader} from "./custom/Headers"
