export {default as HeroSection} from "./hero/hero"
export {default as ServicesSection} from "./our-services/services"
export {default as ProductsSection} from "./products/products"
export {default as ArrivalsSection} from "./new-arivals/newArrival"
// export {default as SubHeader} from "./custom/Headers"
