export {default as HeroSection} from "./components/home/hero/hero"
export {default as ServicesSection} from "./components/home/our-services/services"
export {default as ProductsSection} from "./components/home/products/products"
export {default as ArrivalsSection} from "./components/home/new-arivals/newArrival"
export {default as TestimonialsSection} from "./components/home/testimonials/testimonials"
export {default as CollectionsSection} from "./components/home/collections/collections"
export {default as DiscountSection} from "./components/home/discount/discount"
export {default as AdminLogin} from "./pages/auth/admin/login"
export {default as ClientLogin} from "./pages/auth/customer/login"
export {default as SignUp} from "./pages/signUp/signUp"
export {default as AdminLayout} from "./layouts/dashboards/admin/index"
export {default as AdminStores} from "./pages/Admin/stores"
export {default as CustomersPage} from "./pages/Admin/customers"
// export {default as SubHeader} from "./custom/Headers"
